openapi: 3.0.0
servers:
  - description: Localhost
    url: 'http://localhost:1918'
info:
  description: API for access to filterable and sortable cached collection of WT hotels.
  version: 'will-be-set-at-runtime'
  title: WT search API
paths:
  /:
    get:
      summary: API info
      responses:
        '200':
          description: Basic information about this API instance.
          content:
            application/json:
              schema:
                type: object
                properties:
                  docs:
                    type: string
                    description: Link to the API documentation.
                  info:
                    type: string
                    description: Link to more information about the API.
                  version:
                    type: string
                    description: Deployed API version number.
                  config:
                    type: string
                    description: Which config is the API using.
  /hotels:
    get:
      summary: Get a list of hotels.
      parameters:
        - name: location
          in: query
          description: Filter by distance to the given location(s). Maximum allowed distance in the filter is 200 km.
          required: false
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
          example:
            summary: Only include hotels up to 20 kilometers away from the point denoted by the (50.08, 14.44) lat / long pair.
            value: 50.08,14.44:20
        - name: sortByLocation
          in: query
          description: Sort by distance from given point.
          required: false
          schema:
            type: string
          example:
            summary: Sort by distance from the point denoted by the (50.08, 14.44) lat / long pair.
            value: 50.08,14.44
      responses:
        '200':
          description: A list of hotels matching the input criteria.
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    description: List of resolved hotels.
                    items:
                      $ref: https://raw.githubusercontent.com/windingtree/wt-read-api/3e9f47badeb20d4cf1082e787952ccc4da714e16/docs/swagger.yaml#/components/schemas/HotelListItem
                  next:
                    description: >-
                      Uri to next page of records. When there's no next page,
                      this is not set.
                    $ref: >-
                      https://raw.githubusercontent.com/windingtree/wiki/d0d0b570e5c449e347ed99eb1650b73cec120789/hotel-data-swagger.yaml#/components/schemas/UriType
        '400':
          $ref: '#/components/responses/BadRequestError'
components:
  responses:
    BadRequestError:
      description: The server does not understand the request (HTTP code 400)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    UnprocessableEntityError:
      description: Request body or params validation failed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      title: Error
      description: Default schema for errors returned by API.
      properties:
        status:
          type: number
          description: HTTP status
        code:
          type: string
          description: Computer-readable error. Use this for comparison.
        short:
          type: string
          description: Human-readable error with a short description of the error.
        long:
          type: string
          description: Verbose explanation of what happened.
